services:
  hadoop:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://hadoop:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=1
    volumes:
      - ./hadoop_namenode_data:/hadoop/dfs/name
      - ./data:/data
    networks:
      - hadoop_network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=1
    depends_on:
      - hadoop
    volumes:
      - ./hadoop_datanode_data:/hadoop/dfs/data
    networks:
      - hadoop_network

  spark:
    image: bitnami/spark:3.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - CORE_CONF_fs_defaultFS=hdfs://hadoop:9000
    ports:
      - "8080:8080"  # Spark UI port
      - "7077:7077"  # Spark master port
    volumes:
      - ./spark_data:/opt/spark/work
      - ./data:/data
    networks:
      - hadoop_network
    depends_on:
      - hadoop

  spark-worker:
    image: bitnami/spark:3.5
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - ./spark_data:/opt/spark/work
    depends_on:
      - spark
    networks:
      - hadoop_network
  
  mongo-db:
    image: mongodb/mongodb-community-server:7.0.2-ubi9
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes: 
      - ./mongo_data:/data/db
    networks:
      - hadoop_network

networks:
  hadoop_network:
    driver: bridge