services:
  hadoop:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://hadoop:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=1
    volumes:
      - ./hadoop_namenode_data:/hadoop/dfs/name
      - ./data:/data
    networks:
      - hadoop_network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hadoop:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_replication=1
    depends_on:
      - hadoop
    volumes:
      - ./hadoop_datanode_data:/hadoop/dfs/data
    networks:
      - hadoop_network

  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark-master
    ports:
      - "7077:7077"  # Spark master port
      - "8080:8080"  # Spark master web UI
    networks:
      - hadoop_network

  spark-worker-1:
    image: bitnami/spark:3.5
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_LOCAL_IP=spark-worker-1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    ports:
      - "8081:8080"  # Worker web UI
    networks:
      - hadoop_network

  spark-worker-2:
    image: bitnami/spark:3.5
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_LOCAL_IP=spark-worker-2
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    depends_on:
      - spark-master
    ports:
      - "8082:8080"  # Worker web UI
    networks:
      - hadoop_network
  
  mongo-db:
    image: mongodb/mongodb-community-server:7.0.2-ubi9
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes: 
      - ./mongo_data:/data/db
    networks:
      - hadoop_network

networks:
  hadoop_network:
    driver: bridge